apiVersion: apps/v1
kind: Deployment
metadata:
  name: display-target
spec:
  selector:
    matchLabels:
      app: display-target
  template:
    metadata:
      labels:
        app: display-target
    spec:
      containers:
      - name: display
        image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: display-target
spec:
  type: NodePort
  selector:
    app: display-target
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

